### PR TITLE
fix: prevent gmp-click warnings when using AdvancedMarkerElement

### LINKED ISSUE #611: Google maps warns about using click instead of gmp-click event.
This is the error in the browser console from google maps.

        addListener(a, b) {
            "click" === a && console.warn(`<${this.localName}>: ${"Please use addEventListener('gmp-click', ...) instead of addListener('click', ...)."}`);
            return _.K(this, a, b)
        }
I
I am not getting this error when not using the marker clusterer.

### PR DESCRIPTION
**Pull request by Mobiletainment**
As of February 21, 2024, `google.maps.Marker` is deprecated in favor of `google.maps.marker.AdvancedMarkerElement`. When handling click events:
- Standard `google.maps.Marker` uses the `"click"` event.
- The newer `google.maps.marker.AdvancedMarkerElement` requires `"gmp-click"` instead.

This fixes the warning: `Please use addEventListener('gmp-click', ...) instead of addEventListener('click', ...).` which occurs when advanced markers are used.

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #611 🦕

### CODE REVIEW

File: src/markerclusterer.ts [hunk 1]
```diff
@@ -259,8 +260,20 @@ export class MarkerClusterer extends OverlayViewSafe {
         // Make sure all individual markers are removed from the map.
         cluster.markers.forEach((marker) => MarkerUtils.setMap(marker, null));
         if (this.onClusterClick) {
+          /**
+           * As of February 21, 2024, `google.maps.Marker` is deprecated in favor of
+           * `google.maps.marker.AdvancedMarkerElement`. When handling click events:
+           * - Standard `google.maps.Marker` uses the `"click"` event.
+           * - `AdvancedMarkerElement` requires `"gmp-click"` instead.
+           */
```
Comment (usefulthink) [inline src/markerclusterer.ts:268]:
```suggestion
          // legacy Marker uses 'click' events, whereas AdvancedMarkerElement uses 'gmp-click'
```
